cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "cmake"
brew "grip"
brew "maven"
brew "md5deep"
brew "python"
brew "ripgrep"
brew "vim"
brew "yarn"
cask "google-chrome"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "intellij-idea-ce"
cask "iterm2"
cask "postman"
cask "slack"
